language: node_js
node_js:
  - "12"
dist: trusty 
sudo: required
services: 
  - docker


before_install:
  - docker build -t my_app_image -f .
  - docker run -d -it --name my_app my_app_image


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/my-app
  on:
    branch: master
